// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // 连接池地址（应用运行时 / Vercel 默认）
    url: process.env["DATABASE_URL"],
    // 直连地址（migrate deploy；Neon / Vercel Postgres 建议配置 DIRECT_URL）
    ...(process.env["DIRECT_URL"]
      ? { directUrl: process.env["DIRECT_URL"] }
      : {}),
  },
});
